# Generated by Django 6.1.1 on 2026-10-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_medicamento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='duracao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='quantidade',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
