# Generated by Django 6.1.1 on 2026-10-01 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmacoes', '0001_initial'),
        ('horarios', '0001_initial'),
        ('medicamentos', '0003_medicamento_duracao_medicamento_quantidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmacaodose',
            options={'ordering': ['-data', 'horario_previsto']},
        ),
        migrations.RemoveConstraint(
            model_name='confirmacaodose',
            name='dose_unica_por_horario_data',
        ),
        migrations.AddField(
            model_name='confirmacaodose',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='confirmacaodose',
            name='horario_previsto',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confirmacaodose',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes', to='horarios.horariomedicamento'),
        ),
        migrations.AlterField(
            model_name='confirmacaodose',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('tomado', 'Tomado'), ('atrasado', 'Atrasado'), ('nao_tomado', 'Não tomado')], default='pendente', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='confirmacaodose',
            constraint=models.UniqueConstraint(fields=('usuario', 'medicamento', 'horario_previsto', 'data'), name='dose_unica_por_medicamento_data'),
        ),
    ]
