# Generated by Django 6.1.1 on 2026-10-08 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmacoes', '0002_alter_confirmacaodose_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('aceita', 'Aceita pela Meta'), ('falhou', 'Falhou'), ('entregue', 'Entregue')], default='pendente', max_length=20)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('confirmacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_whatsapp', to='confirmacoes.confirmacaodose')),
            ],
            options={
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('confirmacao', 'telefone'), name='notificacao_unica_por_dose_telefone')],
            },
        ),
    ]
